import { createContext, useContext, useMemo, useState } from 'react';

const STORAGE_KEY = 'ea-csp-locale';

const messages = {
  en: {
    languageLabel: 'Language',
    languages: { en: 'English', 'zh-CN': '简体中文', 'zh-TW': '繁體中文' },
    common: {
      refresh: 'Refresh',
      exportCsv: 'Export CSV',
      subscriptions: 'Subscriptions',
      totalResources: 'Total Resources',
      resourceTypes: 'Resource Types',
      resources: 'Resources',
      dashboard: 'Dashboard',
      assessment: 'Assessment',
      reports: 'Reports',
      logout: 'Logout',
      allSubscriptions: 'All Subscriptions',
      allResourceTypes: 'All Resource Types',
      designedBy: 'Designed by Charles Deng',
      loadingSubscriptions: 'Loading subscriptions...',
      noData: 'No data',
    },
    login: {
      title: 'EA to CSP Assessment',
      description: 'Assess your Azure resources for migration from Enterprise Agreement or Web Direct to Cloud Solution Provider (CSP).',
      supportedAccountTypes: 'Supported account types:',
      directEa: 'Direct Enterprise Agreement (EA)',
      indirectEa: 'Indirect Enterprise Agreement',
      webDirect: 'Web Direct / Pay-As-You-Go',
      signIn: 'Sign in with Azure AD',
      loginFailed: 'Login failed. Please try again.',
      secureSso: 'Secure single sign-on via Microsoft identity platform.',
      credentialsHandled: 'Your credentials are handled entirely by Microsoft — never by us.',
    },
    layout: {
      dashboard: 'Dashboard',
      resources: 'Resources',
      assessment: 'Assessment',
      reports: 'Reports',
      logout: 'Logout',
    },
    dashboard: {
      title: 'Dashboard',
      runAssessment: 'Run Assessment',
      azureSubscriptions: 'Azure Subscriptions',
      subscriptionName: 'Subscription Name',
      subscriptionId: 'Subscription ID',
      state: 'State',
      accountType: 'Account Type',
      resources: 'Resources',
      readyForAssessment: 'Ready for Assessment',
      personalDetected: 'Personal Account Detected',
      personalDescription: 'You are signed in as {username}. Personal Microsoft accounts do not have Azure subscriptions. To view Azure resources and run assessments, please sign in with a work or school account (organizational account).',
      accessError: 'Unable to access Azure resources. Your account may not have Azure subscriptions or the required permissions. Please sign in with a work/school account that has Azure access.',
      loadError: 'Failed to load subscriptions. Please check your authentication.',
      accountTypes: {
        direct_ea: 'Direct EA',
        indirect_ea: 'Indirect EA',
        web_direct: 'Web Direct',
        csp: 'CSP',
        unknown: 'Unknown',
      },
    },
    resourcesPage: {
      title: 'Resource Inventory',
      personalTitle: 'Personal Account',
      personalDescription: 'Signed in as {username}. Personal Microsoft accounts cannot access Azure Resource Manager. To view your Azure resource inventory, please sign out and sign in with a work or school account.',
      accessError: 'Unable to access Azure resources. Please sign in with an account that has Azure access.',
      loadError: 'Failed to load resources.',
      searchPlaceholder: 'Search by name, type, or resource group...',
      resourceName: 'Resource Name',
      type: 'Type',
      resourceGroup: 'Resource Group',
      location: 'Location',
      subscription: 'Subscription',
      totalLabel: 'Total {count} resources',
      csvName: 'azure-resources.csv',
    },
    assessmentPage: {
      title: 'CSP Migration Assessment',
      configure: 'Configure Assessment',
      selectSubscriptions: 'Select Subscriptions',
      overrideAccountType: 'Override Account Type',
      overrideTooltip: 'Override the auto-detected account type if needed',
      autoDetect: 'Auto-detect',
      runAssessment: 'Run Assessment',
      loading: 'Scanning resources and generating assessment...',
      loadError: 'Failed to load subscriptions',
      runError: 'Assessment failed. Please try again.',
      readinessScore: 'Readiness Score',
      keyFindings: 'Key Findings',
      reason: 'Reason',
      recommendations: 'Recommendations',
      risks: 'Risks',
      totalSummary: '{resources} resources across {subscriptions} subscription(s)',
      resource: 'Resource',
      type: 'Type',
      location: 'Location',
      difficulty: 'Difficulty',
      downtime: 'Downtime',
      notAvailable: 'N/A',
      viewReport: 'View Full Report',
      newAssessment: 'Run New Assessment',
      difficulties: {
        easy: 'Easy Transfer',
        moderate: 'Moderate',
        hard: 'Hard / Redeploy',
        not_supported: 'Not Supported',
        needs_review: 'Needs Review',
      },
      overrideOptions: {
        direct_ea: 'Direct EA',
        indirect_ea: 'Indirect EA',
        web_direct: 'Web Direct / PAYG',
      },
    },
    reportPage: {
      title: 'Generate Report',
      description: 'Generate a comprehensive migration assessment report in your preferred format. The report includes readiness scores, per-resource analysis, risk assessments, and actionable recommendations.',
      reportFormat: 'Report Format',
      htmlPreview: 'HTML Preview',
      downloadPdf: 'Download PDF',
      downloadJson: 'Download JSON',
      generate: 'Generate Report',
      generating: 'Generating report...',
      preview: 'Report Preview',
      successPdf: 'PDF report downloaded',
      successJson: 'JSON report downloaded',
      error: 'Failed to generate report. Run an assessment first.',
      pdfName: 'csp-assessment-report.pdf',
      jsonName: 'csp-assessment-report.json',
    },
  },
  'zh-CN': {
    languageLabel: '语言',
    languages: { en: 'English', 'zh-CN': '简体中文', 'zh-TW': '繁體中文' },
    common: {
      refresh: '刷新',
      exportCsv: '导出 CSV',
      subscriptions: '订阅数量',
      totalResources: '资源总数',
      resourceTypes: '资源类型',
      resources: '资源清单',
      dashboard: '仪表板',
      assessment: '评估',
      reports: '报告',
      logout: '退出登录',
      allSubscriptions: '全部订阅',
      allResourceTypes: '全部资源类型',
      designedBy: 'Designed by Charles Deng',
      loadingSubscriptions: '正在加载订阅...',
      noData: '暂无数据',
    },
    login: {
      title: 'EA 转 CSP 评估平台',
      description: '评估 Azure 资源从企业协议 EA 或 Web Direct 迁移到云解决方案提供商 CSP 的准备情况。',
      supportedAccountTypes: '支持的账号类型：',
      directEa: '直接企业协议（EA）',
      indirectEa: '间接企业协议',
      webDirect: 'Web Direct / 按量付费',
      signIn: '使用 Azure AD 登录',
      loginFailed: '登录失败，请重试。',
      secureSso: '通过 Microsoft 身份平台进行安全单点登录。',
      credentialsHandled: '你的凭据完全由 Microsoft 处理，我们不会保存。',
    },
    layout: {
      dashboard: '仪表板',
      resources: '资源清单',
      assessment: '评估',
      reports: '报告',
      logout: '退出登录',
    },
    dashboard: {
      title: '仪表板',
      runAssessment: '开始评估',
      azureSubscriptions: 'Azure 订阅',
      subscriptionName: '订阅名称',
      subscriptionId: '订阅 ID',
      state: '状态',
      accountType: '账号类型',
      resources: '资源数',
      readyForAssessment: '可评估订阅',
      personalDetected: '检测到个人账号',
      personalDescription: '你当前登录账号为 {username}。个人 Microsoft 账号没有 Azure 订阅。如需查看 Azure 资源并执行评估，请使用企业或学校组织账号登录。',
      accessError: '无法访问 Azure 资源。当前账号可能没有 Azure 订阅或缺少所需权限，请使用具备 Azure 访问权限的企业/学校账号登录。',
      loadError: '加载订阅失败，请检查身份验证。',
      accountTypes: {
        direct_ea: '直接 EA',
        indirect_ea: '间接 EA',
        web_direct: 'Web Direct',
        csp: 'CSP',
        unknown: '未知',
      },
    },
    resourcesPage: {
      title: '资源清单',
      personalTitle: '个人账号',
      personalDescription: '当前登录账号为 {username}。个人 Microsoft 账号无法访问 Azure Resource Manager。如需查看 Azure 资源清单，请退出并使用企业或学校账号登录。',
      accessError: '无法访问 Azure 资源，请使用具备 Azure 权限的账号登录。',
      loadError: '加载资源失败。',
      searchPlaceholder: '按名称、类型或资源组搜索...',
      resourceName: '资源名称',
      type: '类型',
      resourceGroup: '资源组',
      location: '区域',
      subscription: '订阅',
      totalLabel: '共 {count} 条资源',
      csvName: 'azure-resources.csv',
    },
    assessmentPage: {
      title: 'CSP 迁移评估',
      configure: '评估配置',
      selectSubscriptions: '选择订阅',
      overrideAccountType: '覆盖账号类型',
      overrideTooltip: '如有需要，可覆盖系统自动识别的账号类型',
      autoDetect: '自动识别',
      runAssessment: '开始评估',
      loading: '正在扫描资源并生成评估结果...',
      loadError: '加载订阅失败',
      runError: '评估失败，请重试。',
      readinessScore: '准备度评分',
      keyFindings: '关键发现',
      reason: '原因',
      recommendations: '建议',
      risks: '风险',
      totalSummary: '共 {resources} 个资源，分布于 {subscriptions} 个订阅',
      resource: '资源',
      type: '类型',
      location: '区域',
      difficulty: '迁移难度',
      downtime: '预计停机',
      notAvailable: '无',
      viewReport: '查看完整报告',
      newAssessment: '重新发起评估',
      difficulties: {
        easy: '易迁移',
        moderate: '中等',
        hard: '困难 / 需重建',
        not_supported: '不支持',
        needs_review: '需人工复核',
      },
      overrideOptions: {
        direct_ea: '直接 EA',
        indirect_ea: '间接 EA',
        web_direct: 'Web Direct / PAYG',
      },
    },
    reportPage: {
      title: '生成报告',
      description: '按你选择的格式生成完整的迁移评估报告。报告包含准备度评分、逐资源分析、风险评估和可执行建议。',
      reportFormat: '报告格式',
      htmlPreview: 'HTML 预览',
      downloadPdf: '下载 PDF',
      downloadJson: '下载 JSON',
      generate: '生成报告',
      generating: '正在生成报告...',
      preview: '报告预览',
      successPdf: 'PDF 报告已下载',
      successJson: 'JSON 报告已下载',
      error: '生成报告失败，请先执行评估。',
      pdfName: 'csp-assessment-report.pdf',
      jsonName: 'csp-assessment-report.json',
    },
  },
  'zh-TW': {
    languageLabel: '語言',
    languages: { en: 'English', 'zh-CN': '简体中文', 'zh-TW': '繁體中文' },
    common: {
      refresh: '重新整理',
      exportCsv: '匯出 CSV',
      subscriptions: '訂閱數量',
      totalResources: '資源總數',
      resourceTypes: '資源類型',
      resources: '資源清單',
      dashboard: '儀表板',
      assessment: '評估',
      reports: '報告',
      logout: '登出',
      allSubscriptions: '全部訂閱',
      allResourceTypes: '全部資源類型',
      designedBy: 'Designed by Charles Deng',
      loadingSubscriptions: '正在載入訂閱...',
      noData: '暫無資料',
    },
    login: {
      title: 'EA 轉 CSP 評估平台',
      description: '評估 Azure 資源從企業協議 EA 或 Web Direct 遷移到雲端解決方案供應商 CSP 的準備情況。',
      supportedAccountTypes: '支援的帳號類型：',
      directEa: '直接企業協議（EA）',
      indirectEa: '間接企業協議',
      webDirect: 'Web Direct / 隨用隨付',
      signIn: '使用 Azure AD 登入',
      loginFailed: '登入失敗，請重試。',
      secureSso: '透過 Microsoft 身分平台進行安全單一登入。',
      credentialsHandled: '你的憑證完全由 Microsoft 處理，我們不會保存。',
    },
    layout: {
      dashboard: '儀表板',
      resources: '資源清單',
      assessment: '評估',
      reports: '報告',
      logout: '登出',
    },
    dashboard: {
      title: '儀表板',
      runAssessment: '開始評估',
      azureSubscriptions: 'Azure 訂閱',
      subscriptionName: '訂閱名稱',
      subscriptionId: '訂閱 ID',
      state: '狀態',
      accountType: '帳號類型',
      resources: '資源數',
      readyForAssessment: '可評估訂閱',
      personalDetected: '偵測到個人帳號',
      personalDescription: '你目前登入的帳號是 {username}。個人 Microsoft 帳號沒有 Azure 訂閱。如需查看 Azure 資源並執行評估，請使用企業或學校組織帳號登入。',
      accessError: '無法存取 Azure 資源。目前帳號可能沒有 Azure 訂閱或缺少必要權限，請使用具有 Azure 存取權限的企業/學校帳號登入。',
      loadError: '載入訂閱失敗，請檢查驗證狀態。',
      accountTypes: {
        direct_ea: '直接 EA',
        indirect_ea: '間接 EA',
        web_direct: 'Web Direct',
        csp: 'CSP',
        unknown: '未知',
      },
    },
    resourcesPage: {
      title: '資源清單',
      personalTitle: '個人帳號',
      personalDescription: '目前登入的帳號是 {username}。個人 Microsoft 帳號無法存取 Azure Resource Manager。如需查看 Azure 資源清單，請登出並使用企業或學校帳號登入。',
      accessError: '無法存取 Azure 資源，請使用具有 Azure 權限的帳號登入。',
      loadError: '載入資源失敗。',
      searchPlaceholder: '依名稱、類型或資源群組搜尋...',
      resourceName: '資源名稱',
      type: '類型',
      resourceGroup: '資源群組',
      location: '區域',
      subscription: '訂閱',
      totalLabel: '共 {count} 筆資源',
      csvName: 'azure-resources.csv',
    },
    assessmentPage: {
      title: 'CSP 遷移評估',
      configure: '評估設定',
      selectSubscriptions: '選擇訂閱',
      overrideAccountType: '覆寫帳號類型',
      overrideTooltip: '如有需要，可覆寫系統自動偵測的帳號類型',
      autoDetect: '自動偵測',
      runAssessment: '開始評估',
      loading: '正在掃描資源並產生評估結果...',
      loadError: '載入訂閱失敗',
      runError: '評估失敗，請重試。',
      readinessScore: '準備度分數',
      keyFindings: '關鍵發現',
      reason: '原因',
      recommendations: '建議',
      risks: '風險',
      totalSummary: '共 {resources} 個資源，分布於 {subscriptions} 個訂閱',
      resource: '資源',
      type: '類型',
      location: '區域',
      difficulty: '遷移難度',
      downtime: '預估停機',
      notAvailable: '無',
      viewReport: '查看完整報告',
      newAssessment: '重新執行評估',
      difficulties: {
        easy: '容易遷移',
        moderate: '中等',
        hard: '困難 / 需重建',
        not_supported: '不支援',
        needs_review: '需人工複核',
      },
      overrideOptions: {
        direct_ea: '直接 EA',
        indirect_ea: '間接 EA',
        web_direct: 'Web Direct / PAYG',
      },
    },
    reportPage: {
      title: '產生報告',
      description: '以你選擇的格式產生完整的遷移評估報告。報告包含準備度分數、逐資源分析、風險評估與可執行建議。',
      reportFormat: '報告格式',
      htmlPreview: 'HTML 預覽',
      downloadPdf: '下載 PDF',
      downloadJson: '下載 JSON',
      generate: '產生報告',
      generating: '正在產生報告...',
      preview: '報告預覽',
      successPdf: 'PDF 報告已下載',
      successJson: 'JSON 報告已下載',
      error: '產生報告失敗，請先執行評估。',
      pdfName: 'csp-assessment-report.pdf',
      jsonName: 'csp-assessment-report.json',
    },
  },
};

const LanguageContext = createContext(null);

function getMessage(locale, path) {
  return path.split('.').reduce((acc, key) => acc?.[key], messages[locale]);
}

function formatMessage(template, params) {
  if (!params || typeof template !== 'string') return template;
  return Object.entries(params).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    template
  );
}

export function LanguageProvider({ children }) {
  const [locale, setLocaleState] = useState(() => localStorage.getItem(STORAGE_KEY) || 'en');

  const setLocale = (nextLocale) => {
    localStorage.setItem(STORAGE_KEY, nextLocale);
    setLocaleState(nextLocale);
  };

  const value = useMemo(() => ({
    locale,
    setLocale,
    t: (path, params) => {
      const current = getMessage(locale, path);
      const fallback = getMessage('en', path);
      return formatMessage(current ?? fallback ?? path, params);
    },
    languageOptions: [
      { value: 'en', label: messages[locale].languages.en },
      { value: 'zh-CN', label: messages[locale].languages['zh-CN'] },
      { value: 'zh-TW', label: messages[locale].languages['zh-TW'] },
    ],
  }), [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}